places = ['dubai', 'america','canada','antarctica','alaska']
print(" Orignal list")
print(places)
print(" Temperory sorted list ")
print(sorted(places))
print(" Orignal list")
print(places)
sortedlist = sorted(places)
sortedlist.reverse()
print(sortedlist)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
places.reverse()
print(places)